// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Cart struct {
	CartID     int       `gorm:"column:cart_id;primary_key;AUTO_INCREMENT"`
	CustomerID int       `gorm:"column:customer_id;NOT NULL"`
	CartName   string    `gorm:"column:cart_name"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP"`
	CustomerIDData Customer `gorm:"foreignKey:CustomerID;references:customer_id"`
}

func (m *Cart) TableName() string {
	return "cart"
}

type cartDetails struct {
	CartName string `json:"cart_name"`
	Items []struct {
		ProductName string  `json:"product_name"`
		Quantity    int     `json:"quantity"`
		Price       float64 `json:"price"`
		TotalPrice  float64 `json:"total_price"`
	} `json:"items"`
}